[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "aiondemand"
authors = [{name = "AI4EU", email = "noreply@aiondemand.com"}]
dynamic = ["version", "description"]
